# Generated by Django 5.2.7 on 2025-10-20 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_postcomment_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='postcomment',
            index=models.Index(fields=['-created_at'], name='blog_postco_created_c540c9_idx'),
        ),
    ]
